# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    #client_base_url: '%env(CLIENT_BASE_URL)%'
    #server_base_url: '%env(SERVER_BASE_URL)%'
    #client_registration_url: '%env(CLIENT_REGISTRATION_URL)%'
    #client_registration_path: '%env(CLIENT_REGISTRATION_PATH)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        #bind:
         #   $clientBaseUrl: '%client_base_url%'
          #  $clientRegistrationPath: '%client_registration_path%'
           # $serverBaseUrl: '%server_base_url%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    s_immo.event.authentication_success_listener:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }


